In [44]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(r"C:\Users\Ramya Oli\OneDrive\Desktop\COLLEGE ASSIGNMENTS\data science\uber_blr\data\bangalore_ride_data.csv")

In [3]:
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer Reason,Cancelled Rides by Driver Reason,Incomplete Ride Reason,Booking Value,Payment Method,Ride Distance,Driver Ratings,Customer Ratings
0,2024-01-15,14:15:00,BKG000001,Success,CUST40172,eBike,Benson Town,Magadi Road,6.83,7.45,NaN,NaN,NaN,881.71,UPI,2.52,1.7,3.2
1,2024-01-28,09:50:00,BKG000002,Incomplete,CUST43954,Moto,Cox Town,Indiranagar,5.11,5.31,NaN,NaN,Vehicle Breakdown,0.00,NaN,0.00,NaN,NaN
2,2024-01-06,03:33:00,BKG000003,Success,CUST95942,Go Sedan,Mahadevapura,Whitefield,14.90,9.64,NaN,NaN,NaN,1458.30,Wallet,26.20,1.1,2.4
3,2024-01-07,01:28:00,BKG000004,Success,CUST15911,Go Sedan,RT Nagar,Nagarbhavi,10.53,9.50,NaN,NaN,NaN,1323.55,Wallet,26.20,3.1,3.7
4,2024-01-07,07:32:00,BKG000005,Success,CUST94242,Uber Go,Basavanagudi,Vijayanagar,8.83,5.75,NaN,NaN,NaN,1999.27,Cash,27.58,2.1,2.8

In [4]:
df.describe()

,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Ratings
count,200000.000000,200000.000000,200000.000000,200000.000000,124164.000000,124164.000000
mean,8.999145,6.996457,634.848029,9.626969,2.997194,3.002977
std,3.461673,2.882076,666.244078,10.010601,1.156227,1.154922
min,3.000000,2.000000,0.000000,0.000000,1.000000,1.000000
25%,6.010000,4.510000,0.000000,0.000000,2.000000,2.000000
50%,9.000000,7.000000,428.655000,6.630000,3.000000,3.000000
75%,11.990000,9.490000,1212.775000,18.340000,4.000000,4.000000
max,15.000000,12.000000,1999.960000,30.000000,5.000000,5.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 18 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Date                                200000 non-null  object
 1   Time                                200000 non-null  object
 2   Booking ID                          200000 non-null  object
 3   Booking Status                      200000 non-null  object
 4   Customer ID                         200000 non-null  object
 5   Vehicle Type                        200000 non-null  object
 6   Pickup Location                     200000 non-null  object
 7   Drop Location                       200000 non-null  object
 8   Avg VTAT                            200000 non-null  float64
 9   Avg CTAT                            200000 non-null  float64
 10  Cancelled Rides by Customer Reason  14191 non-null   object
 11  Cancelled Rides by Driver Reason    35873 non-null   object
 12  Incomplete Ride Reason              25772 non-null   object
 13  Booking Value                       200000 non-null  float64
 14  Payment Method                      124164 non-null  object
 15  Ride Distance                       200000 non-null  float64
 16  Driver Ratings                      124164 non-null  float64
 17  Customer Ratings                    124164 non-null  float64
dtypes: float64(6), object(12)
memory usage: 27.5+ MB

In [6]:
df.columns

Index(['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT', 'Cancelled Rides by Customer Reason',
       'Cancelled Rides by Driver Reason', 'Incomplete Ride Reason',
       'Booking Value', 'Payment Method', 'Ride Distance', 'Driver Ratings',
       'Customer Ratings'],
      dtype='object')

In [7]:
df["Booking Status"].value_counts()

Booking Status
Success                  124164
Cancelled by Driver       35873
Incomplete                25772
Cancelled by Customer     14191
Name: count, dtype: int64

In [8]:
df["Cancelled Rides by Customer Reason"].value_counts()

Cancelled Rides by Customer Reason
AC is not working                               2927
Driver asked to cancel                          2863
Change of plans                                 2838
Driver is not moving towards pickup location    2795
Wrong Address                                   2768
Name: count, dtype: int64

In [9]:
df['Cancelled Rides by Driver Reason'].value_counts()

Cancelled Rides by Driver Reason
More than permitted people in there    9029
The customer was coughing/sick         9013
Customer related issue                 8989
Personal & Car related issues          8842
Name: count, dtype: int64

In [10]:
df['Hour'] = pd.to_datetime(df['Time'], format='%H:%M:%S').dt.hour
df['Hour'].value_counts()

Hour
21    8610
16    8458
8     8446
6     8426
7     8413
14    8407
10    8391
0     8383
9     8369
4     8357
18    8348
12    8327
20    8324
13    8314
3     8302
1     8298
17    8278
5     8259
19    8255
22    8237
23    8227
15    8204
11    8203
2     8164
Name: count, dtype: int64

In [11]:
cancelled_driver_based_on_pickup = df[df["Booking Status"]=="Cancelled by Driver"]
cancelled_driver_based_on_pickup["Pickup Location"].value_counts()

Pickup Location
Kudlu Gate           754
Koramangala          753
Vidyaranyapura       748
Lingarajapuram       735
Basaveshwaranagar    734
Vijayanagar          730
Whitefield           728
Sarjapur Road        728
HSR Layout           727
Basavanagudi         725
Marathahalli         724
Mahadevapura         723
Bommanahalli         719
MG Road              717
RT Nagar             716
Magadi Road          710
Richmond Town        708
Hebbal               706
Frazer Town          706
Dasarahalli          705
Jayanagar            705
KR Puram             704
Cox Town             703
Hulimavu             703
Kammanahalli         702
Nagarbhavi           701
Malleswaram          701
Rajajinagar          696
Devanahalli          695
Yeshwanthpur         695
Varthur              695
Kadugodi             695
Anekal               693
Yelahanka            693
Shivaji Nagar        693
Hormavu              692
Bellandur            692
JP Nagar             691
Kengeri              690
Ulsoor               689
BTM Layout           688
Bannerghatta Road    687
CV Raman Nagar       685
Indiranagar          684
Banashankari         679
Domlur               675
Hosur Road           675
Hennur               673
Sadashivanagar       671
Benson Town          669
Electronic City      663
Name: count, dtype: int64

So this uniform distribution tells that this dataset is synthetic and not based on real life

In [12]:
cancelled_driver_based_on_drop = df[df["Booking Status"]=="Cancelled by Driver"]

In [13]:
cancelled_driver_based_on_drop["Drop Location"].value_counts()

Drop Location
Yelahanka            750
Cox Town             749
Frazer Town          744
Dasarahalli          740
Kudlu Gate           738
Ulsoor               737
Kammanahalli         735
Hormavu              734
Domlur               731
Kengeri              728
Hennur               727
Yeshwanthpur         726
Basavanagudi         725
Devanahalli          723
Hulimavu             721
Kadugodi             720
Bannerghatta Road    718
Bommanahalli         716
CV Raman Nagar       715
Koramangala          713
Magadi Road          712
Lingarajapuram       711
Mahadevapura         709
Hebbal               709
Rajajinagar          704
Electronic City      703
Varthur              703
Marathahalli         700
HSR Layout           699
Sarjapur Road        699
Hosur Road           698
RT Nagar             698
Benson Town          695
Whitefield           693
Malleswaram          693
Indiranagar          692
Sadashivanagar       691
MG Road              689
Vidyaranyapura       689
JP Nagar             688
Banashankari         687
Basaveshwaranagar    677
Richmond Town        674
Bellandur            665
Anekal               663
Shivaji Nagar        662
KR Puram             661
Vijayanagar          660
Nagarbhavi           658
BTM Layout           656
Jayanagar            645
Name: count, dtype: int64

In [14]:
cancelled_drivers = df[df["Booking Status"].isin(["Cancelled by Driver","Incomplete","Cancelled by Customer "])]

In [15]:
total = df["Pickup Location"].value_counts()
cancelled = cancelled_drivers["Pickup Location"].value_counts()

rate = (cancelled / total) * 100

In [16]:
rate.idxmax()
rate.idxmin()

'JP Nagar'

In [17]:
rate.describe()

count    51.000000
mean     30.824563
std       0.684273
min      28.713629
25%      30.394883
50%      30.858411
75%      31.270939
max      32.104873
Name: count, dtype: float64

In [18]:
total_vehicle=df["Vehicle Type"].value_counts()
total_vehicle

Vehicle Type
UberXL         28826
Go Sedan       28717
Premier        28685
Non-AC Taxi    28573
eBike          28558
Moto           28478
Uber Go        28163
Name: count, dtype: int64

In [19]:
cancelled_by_vehicle = cancelled_drivers["Vehicle Type"]
cancelled_by_vehicle_count = cancelled_by_vehicle.value_counts()

In [20]:
rate_by_vehicle = (cancelled_by_vehicle_count/total_vehicle)*100

In [21]:
rate_by_vehicle

Vehicle Type
Go Sedan       30.988613
Moto           30.623639
Non-AC Taxi    30.619816
Premier        30.730347
Uber Go        30.767319
UberXL         31.121210
eBike          30.902024
Name: count, dtype: float64

So here we can see again

In [22]:
df.isna().value_counts()

Date   Time   Booking ID  Booking Status  Customer ID  Vehicle Type  Pickup Location  Drop Location  Avg VTAT  Avg CTAT  Cancelled Rides by Customer Reason  Cancelled Rides by Driver Reason  Incomplete Ride Reason  Booking Value  Payment Method  Ride Distance  Driver Ratings  Customer Ratings  Hour
False  False  False       False           False        False         False            False          False     False     True                                True                              True                    False          False           False          False           False             False    124164
                                                                                                                                                             False                             True                    False          True            False          True            True              False     35873
                                                                                                                                                             True                              False                   False          True            False          True            True              False     25772
                                                                                                                         False                               True                              True                    False          True            False          True            True              False     14191
Name: count, dtype: int64

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 19 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Date                                200000 non-null  object
 1   Time                                200000 non-null  object
 2   Booking ID                          200000 non-null  object
 3   Booking Status                      200000 non-null  object
 4   Customer ID                         200000 non-null  object
 5   Vehicle Type                        200000 non-null  object
 6   Pickup Location                     200000 non-null  object
 7   Drop Location                       200000 non-null  object
 8   Avg VTAT                            200000 non-null  float64
 9   Avg CTAT                            200000 non-null  float64
 10  Cancelled Rides by Customer Reason  14191 non-null   object
 11  Cancelled Rides by Driver Reason    35873 non-null   object
 12  Incomplete Ride Reason              25772 non-null   object
 13  Booking Value                       200000 non-null  float64
 14  Payment Method                      124164 non-null  object
 15  Ride Distance                       200000 non-null  float64
 16  Driver Ratings                      124164 non-null  float64
 17  Customer Ratings                    124164 non-null  float64
 18  Hour                                200000 non-null  int32
dtypes: float64(6), int32(1), object(12)
memory usage: 28.2+ MB

In [24]:
df['day_of_week'] = pd.to_datetime(df['Date'], format='%Y-%m-%d').dt.dayofweek

In [25]:
data = df.drop(["Booking ID","Customer ID","Cancelled Rides by Customer Reason","Cancelled Rides by Driver Reason","Incomplete Ride Reason","Driver Ratings","Customer Ratings"],axis=1)

In [26]:
target_var = df["Booking Status"]

In [27]:
type(target_var)

pandas.core.series.Series

In [29]:
data.drop(["Payment Method","Date","Time","Booking Status"],axis=1,inplace=True)

In [30]:
data.columns

Index(['Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT', 'Booking Value', 'Ride Distance', 'Hour', 'day_of_week'],
      dtype='object')

In [32]:
data["Vehicle Type"].value_counts()

Vehicle Type
UberXL         28826
Go Sedan       28717
Premier        28685
Non-AC Taxi    28573
eBike          28558
Moto           28478
Uber Go        28163
Name: count, dtype: int64

we are converting this from strings to category because we are letting lightgbm handle the encoding for this and it needs it to be in the category type

In [34]:
data['Pickup Location'] = data['Pickup Location'].astype('category')
data['Drop Location'] = data['Drop Location'].astype('category')

In [39]:
encoder = LabelEncoder()
data["vehicle_encoded"] = encoder.fit_transform(data["Vehicle Type"])

In [42]:
data.drop(["Vehicle Type"],axis=1,inplace=True)

In [43]:
data.columns

Index(['Pickup Location', 'Drop Location', 'Avg VTAT', 'Avg CTAT',
       'Booking Value', 'Ride Distance', 'Hour', 'day_of_week',
       'vehicle_encoded'],
      dtype='object')

In [ ]:
target_var = np.where(df["Booking Status"]=="Cancelled by Driver",1,0)

Booking Status
Success                  124164
Cancelled by Driver       35873
Incomplete                25772
Cancelled by Customer     14191
Name: count, dtype: int64

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(data,target_var,random_state=42,test_size=0.2)